/**
 * Schema for the `notes` table.
 * Call notes and system-generated disposition logs tied to a business.
 */
export interface Note {
  id: number;
  business_id: number;
  body: string;
  /** 1 = auto-generated by system (e.g. status change), 0 = manual agent note */
  is_system_generated: 0 | 1;
  created_ts: Date;
}
